config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/about'
  get 'pages/team'
  root 'pages#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def team
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrimerRor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= image_tag 'logo.png', id:'logo', alt:'Logo Orbo Chile', height:'50vh', class:'barra'%>
    <br>
    <p class='barra' id='menu'>
      <a href="<%= pages_index_path %>"> Índice</a>
      <a href="<%= pages_about_path %>"> Sobre nosotros</a>
      <a href="<%= pages_team_path %>"> Nuestro Equipo</a>
    </p>
    <%= yield %>
    <h5> Orbo Chile </h5>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<h4>Estoy generando cambios</h4>  
<h6>Estoy generando cambios</h6>  
<p>Find me in app/views/pages/index.html.erb</p>
<br>
©Copyright <%= Time.now.year %>
<br>
<% if Time.now.year >= 2020 %>
    <p> Versión 2.0 </p>
    <% else %>
    <p> Versión 1.0 </p>
<% end %>

app/views/pages/team.html.erb
<h1>Contenido de la página team.html.erb</h1>